### ISSUE TITLE
Removing node_modules

### ISSUE THREAD

**Issue by shawshankkumar** [sid-khuntwal/lexical-cli-hacktoberfest#1]
node_modules should not be pushed to the upstream branch.

**Comment by shawshankkumar** [comment]
Hey, @sid-khuntwal can I fix this?

**Comment by sid-khuntwal** [comment]
Yes, go ahead @shawshankkumar

**Comment by shawshankkumar** [comment]
@sid-khuntwal can you add contributing.md and readme.md too
