### ISSUE TITLE
Adding certain details before you add this repo in Hacktoberfest

### ISSUE THREAD

**Issue by arpitghura** [sid-khuntwal/lexical-cli-hacktoberfest#4]
Hey, @sid-khuntwal if you would like to add this repo in Hacktoberfest then you should have to do some things with the repo

1. Add the `Hacktoberfest` and `Hacktoberfest-2022` tags under the repo description.
2. If you are planning to merge any PR under Hacktoberfest, please add the `Hacktoberfest` and `hactoberfest-accepted` labels on the PR.
3. and for issues, add a `Hacktoberfest` label.
4. Also try to improve the documentation of the project.

Btw, You did a great job by adding your personal project to GitHub to help the community.

**Comment by sid-khuntwal** [comment]
Would you like to do @arpitghura ?

**Comment by arpitghura** [comment]
> Would you like to do @arpitghura ?

Thank you for considering me but this thing can only be done by the project/repo owner. 

I can tell you the steps by which you can do this.
1. Open the `code` tab of the repo 
2. On the right sidebar, you find certain details about the repo.
3. Tap the `settings` icon and then a popup opens
4. Under that popup model, you will find the `Tags` option. 
5. In the tags section, add both tags and save them.
6. You are good to go, the repo will be included as part of Hacktoberfest 2022.

**Comment by sid-khuntwal** [comment]
Thanks!
